/// Generated by spider on 2026-02-02 16:35:00.507599

import 'dart:io';

import 'package:Quan_ly_thu_chi_PRM/core/constants/resources.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('icon_path assets test', () {
    expect(File(IconPath.arrowLeft).existsSync(), isTrue);
  });
}
