/// Generated by spider on 2026-02-22 09:50:18.788983

import 'dart:io';

import 'package:Quan_ly_thu_chi_PRM/core/constants/resources.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('icon_path assets test', () {
    expect(File(IconPath.arrowLeft).existsSync(), isTrue);
    expect(File(IconPath.check).existsSync(), isTrue);
    expect(File(IconPath.circleCheck).existsSync(), isTrue);
    expect(File(IconPath.home).existsSync(), isTrue);
    expect(File(IconPath.ledger).existsSync(), isTrue);
    expect(File(IconPath.plans).existsSync(), isTrue);
    expect(File(IconPath.settings).existsSync(), isTrue);
    expect(File(IconPath.stats).existsSync(), isTrue);
  });
}
