/// Generated by spider on 2026-01-27 23:37:37.602626

import 'dart:io';

import 'package:Quan_ly_thu_chi_PRM/core/constants/resources.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('images assets test', () {
    expect(File(Images.splashLogo).existsSync(), isTrue);
  });
}
