/// Generated by spider on 2026-02-22 09:50:18.840270

import 'dart:io';

import 'package:Quan_ly_thu_chi_PRM/core/constants/resources.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('images assets test', () {
    expect(File(Images.changePwSuccessLogo).existsSync(), isTrue);
    expect(File(Images.house).existsSync(), isTrue);
    expect(File(Images.lockLogo).existsSync(), isTrue);
    expect(File(Images.signupLogo).existsSync(), isTrue);
    expect(File(Images.splashLogo).existsSync(), isTrue);
    expect(File(Images.tesla).existsSync(), isTrue);
    expect(File(Images.walletLogo).existsSync(), isTrue);
  });
}
