/// Generated by spider on 2026-01-28 21:26:38.677314

import 'dart:io';

import 'package:Quan_ly_thu_chi_PRM/core/constants/resources.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('images assets test', () {
    expect(File(Images.lockLogo).existsSync(), isTrue);
    expect(File(Images.signupLogo).existsSync(), isTrue);
    expect(File(Images.splashLogo).existsSync(), isTrue);
  });
}
