// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGgKLJGwGKeqQnwz-Quwrj6eTBSXzPP4c',
    appId: '1:279622842154:web:141d78a853b05e8e9cd053',
    messagingSenderId: '279622842154',
    projectId: 'quanlythuchiprm',
    authDomain: 'quanlythuchiprm.firebaseapp.com',
    databaseURL: 'https://quanlythuchiprm-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quanlythuchiprm.firebasestorage.app',
    measurementId: 'G-32BYWQL288',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCerhfTKm_yd3WyQCCfqFAhPLyBzp4Cbto',
    appId: '1:279622842154:android:985a49d6b5b509fa9cd053',
    messagingSenderId: '279622842154',
    projectId: 'quanlythuchiprm',
    databaseURL: 'https://quanlythuchiprm-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quanlythuchiprm.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGgKLJGwGKeqQnwz-Quwrj6eTBSXzPP4c',
    appId: '1:279622842154:web:907ba49cc73dbf7b9cd053',
    messagingSenderId: '279622842154',
    projectId: 'quanlythuchiprm',
    authDomain: 'quanlythuchiprm.firebaseapp.com',
    databaseURL: 'https://quanlythuchiprm-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quanlythuchiprm.firebasestorage.app',
    measurementId: 'G-QEZ1C8C6CR',
  );

}