// Generated by spider on 2026-02-06 09:21:46.452444

part of 'resources.dart';

class IconPath {
  IconPath._();

  static const String arrowLeft = 'assets/icons/arrow_left.svg';
  static const String check = 'assets/icons/check.svg';
  static const String circleCheck = 'assets/icons/circle_check.svg';
}
