// Generated by spider on 2026-02-25 13:54:33.298065

part of 'resources.dart';

class IconPath {
  IconPath._();

  static const String arrowLeft = 'assets/icons/arrow_left.svg';
  static const String check = 'assets/icons/check.svg';
  static const String circleCheck = 'assets/icons/circle_check.svg';
  static const String filter = 'assets/icons/filter.svg';
  static const String home = 'assets/icons/home.svg';
  static const String ledger = 'assets/icons/ledger.svg';
  static const String plans = 'assets/icons/plans.svg';
  static const String search = 'assets/icons/search.svg';
  static const String settings = 'assets/icons/settings.svg';
  static const String stats = 'assets/icons/stats.svg';
}
