// Generated by spider on 2026-02-06 09:21:46.598850

part of 'resources.dart';

class Images {
  Images._();

  static const String changePwSuccessLogo =
      'assets/images/change_pw_success_logo.png';
  static const String lockLogo = 'assets/images/lock_logo.png';
  static const String signupLogo = 'assets/images/signup_logo.png';
  static const String splashLogo = 'assets/images/splash_logo.png';
  static const String walletLogo = 'assets/images/wallet_logo.png';
}
